<?php $this->setPageTitle("Gympik- An end-to-end free online platform to help improving lifestyle choices.");?>

<!--  <div class="row-fluid">
    <div class="span12">
      <h1>All About Nutrition.</h1>
    </div>
  </div>-->
  <div class="row-fluid detail">
    	<h3>Get Big, Not Fat: A Better Approach To Bulk And Build Muscle</h3>
        <img class="imgfl" src="<?php echo Yii::app()->request->baseUrl; ?>/images/get-big-not-fat.jpg" alt="" />
<p>Every bodybuilder wants to get big. Unfortunately, in their zeal to get big many bodybuilders overeat and end up big alright, big and fat. Some bodybuilders seem to go from training for a bodybuilding contest to training for an eating contest once their season is over. Obviously, this is not a recipe for success. If you really want to win your next show, the time to do it is in the offseason.</p>
      <p>You will need to add as much size as possible while keeping fat gain under control because trying to diet off 50lbs before a contest is not the best strategy. You will have to cut calories too low and for too long to get all that weight off, and will inevitably lose some of that hard-earned muscle. You will probably not even be able to get as lean as you could have because dieting as long and as hard as it takes to lose 50lbs. for a show spells disaster for your metabolism. Sometimes even those with the best intentions to stay lean during the offseason can’t seem to do it.  So is it possible to add maximum size while staying lean? YES!</p>
      <p>Let’s look at the typical offseason of a very ambitious bodybuilder. As soon as his last show is over he begins laying out the perfect diet to add size without getting too heavy. Once he has laid down the perfect plan he will tell no less than three people “By next year I’m gonna be huge, bro!” He will probably gain only about 1-2 lb. per week with his plan.</p>
      <p>Slowly he will make great gains and after about 3 weeks he’ll be about 6lbs. heavier. Everything is going well until he finds out he has to go to his cousin's wedding. At the reception he’ll have a few drinks and enjoy himself for an evening. He hasn’t cheated in 3 weeks so he thinks it is ok. The next morning his weight has jumped 2lbs. He goes right back on the diet and gains another 3lbs. over the next two weeks.</p>
      <p>There is a simple answer to this problem. Cut calories. Many competitors never cut calories during the offseason for fear that it will interrupt the “awesome gains” they have been making. The mantra of “you’ve gotta eat big to get big” is more often used as an excuse to pig out than an actual effective method of putting on size. Not all of the fears about cutting calories are wrong, because if done too drastically and for too long it impedes progress. But, keeping fat under control does involve cutting calories.</p>
      <p>I am not talking about going into a full on contest diet but systematic and well planned increases and decreases will allow you to keep making gains uninterrupted and help keep body fat to a minimum. When on a diet the first few weeks are always the easiest. You lose fat very easily and don’t lose muscle size or strength. This is because when calories and carbs are high fat burning hormones are as well.</p>
      <p>One of these hormones is T3. T3 is a thyroid hormone that helps regulate body temperature. It helps your cells take the carbs and calories that you eat and efficiently turn them into energy and heat. This means that when T3 levels are high, calories are less likely stored as fat and are more likely going to be used as energy. When calories are restricted for prolonged periods the body will try to conserve energy by dropping T3 levels, allowing less calories to be used as energy and heat. This is one of the reasons why people on contest diets often complain about feeling cold.</p>
      <img src="<?php echo Yii::app()->request->baseUrl ?>/images/shredded-bodybuilder.jpg" alt=""  class="imgfr"/>
<p>Also helping to control energy expenditure is the hormone leptin. Leptin increases thermogenesis by reacting with the sympathetic nervous system. Leptin also works with the central nervous system to control eating drive. When leptin levels are high it is a signal to your body that you do not need to consume additional calories. Having high leptin levels just may help you cut down on some of those “bonus calories” that always seem to find their way into your diet. Although leptin levels tend to be primarily raised and lowered in relation to body fat, you can cause increases and decreases by overfeeding and underfeeding.</p>
<p>Also helping to control energy expenditure is the hormone leptin. Leptin increases thermogenesis by reacting with the sympathetic nervous system. Leptin also works with the central nervous system to control eating drive. When leptin levels are high it is a signal to your body that you do not need to consume additional calories. Having high leptin levels just may help you cut down on some of those “bonus calories” that always seem to find their way into your diet. Although leptin levels tend to be primarily raised and lowered in relation to body fat, you can cause increases and decreases by overfeeding and underfeeding.</p>
<p>When you drop calories your body does not react immediately to adjust your metabolism. So for the first couple of weeks your metabolism is still running at full capacity with levels of T3 and leptin remaining high. This allows you to lose plenty of fat without having to lower calories to drastically low levels. After a couple of weeks your body will adjust and losing at the same rate will be difficult.</p>
<p>If this were a contest diet you would continue to grind it out at a slower pace or lower calories further, but this is the offseason and fat loss is not the primary goal. Your goal is only to keep body fat in check while continuing to gain size, so you will want to bring calories back up before this shift in metabolism occurs. This way you can continue right on your way getting stronger and gaining muscle while occasionally keeping body fat levels from creeping to high.</p><p>Most bodybuilders have concerns about cutting calories in the offseason for fear that it will interrupt muscle growth and they will not be as big at their next show. Now of course staying leaner in the offseason will help you be leaner on show day but it will also allow you to step on stage with more muscle as well. When you bring calories down for only short spurts your anabolic hormones such as testosterone and growth hormone remain high.</p><p>Also, as long as carbs are not lowered to far for too long insulin sensitivity will remain high. This means that during the periods of lower calories your body will continue to use calories for muscle growth while losing some excess adipose tissue. A drop in carbs during these low calorie periods may even lead to an increase in growth hormone levels due to the lower circulating glucose levels in your bloodstream. These lower calorie spurts must not be too long nor should the decrease in calories be too severe or you run the risk of slowing muscle growth. This risk is precisely the reason you will be more muscular on stage using this method of gaining size.</p>	
    </div>
  

